server:
  port: 8911

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxl-job?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password:  123456

mybatis:
  config-location: classpath:mappers/config.xml
  mapper-locations: classpath:mappers/mapper/*.xml
